config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('pages.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
] + urlpatterns

pages/urls.py
from django.urls import path

from .views import *
from . import views

app_name = 'locdata'

urlpatterns = [
    #path('', HomePageView.as_view(), name='home'),
    path('', views.index, name='index'),
    path('<int:locdata_id>', views.detail, name='detail'),
    path('about/', AboutPageView.as_view(), name='about'),
    path('contactTracing/', views.contactTracing, name='Contact Tracing'),
    path('assetManagement/', views.assetManagement, name='Asset Management'),
    path('changePermissions/', views.changePermissions, name='Change Permissions'),
    path('bTest/', views.homepage, name='Home')
]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class CustomUser(AbstractUser):
    pass

    def __str__(self):
        return self.email

pages/models.py
from django.db import models

# Create your models here.
class Tblassets(models.Model):
    assettype = models.SmallIntegerField(db_column='assetType', blank=True, null=True)  # Field name made lowercase.
    firstname = models.CharField(db_column='firstName', max_length=255, blank=True, null=True)  # Field name made lowercase.
    lastname = models.CharField(db_column='lastName', max_length=255, blank=True, null=True)  # Field name made lowercase.
    identifier = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self):
        if self.identifier == None:
            return str(self.firstname) + ' ' + str(self.lastname)
        else:
            return str(self.identifier)

    class Meta:
        managed = False
        db_table = 'tblassets'


class Tblbadges(models.Model):
    badgeid = models.IntegerField(db_column='badgeID', blank=True, null=True)  # Field name made lowercase.
    asset = models.ForeignKey(Tblassets, models.DO_NOTHING, db_column='asset', blank=True, null=True)
    lastbatterychange = models.DateTimeField(db_column='lastBatteryChange', blank=True, null=True)  # Field name made lowercase.

    def __str__(self):
        return str(self.badgeid) + ', ' + str(self.asset)
    class Meta:
        managed = False
        db_table = 'tblbadges'


class Tbllocationdata(models.Model):
    id = models.BigAutoField(primary_key=True)
    nodeid = models.IntegerField(db_column='nodeID', blank=True, null=True)  # Field name made lowercase.
    badgeid = models.IntegerField(db_column='badgeID', blank=True, null=True)  # Field name made lowercase.
    stampedtime = models.DateTimeField(db_column='stampedTime', blank=True, null=True)  # Field name made lowercase.

    def __str__(self):
        r = Tblnodes.objects.filter(nodeid=self.nodeid)
        a = Tblbadges.objects.filter(badgeid=self.badgeid)
        if len(a) > 0 and len(r) > 0:
            return str(a[0].asset) + ', Room ' + str(r[0].room) + ' on ' + str(self.stampedtime)
        else:
            return str(self.nodeid) + ',' + str(self.badgeid) + ',' + str(self.stampedtime)
    class Meta:
        managed = False
        db_table = 'tbllocationdata'


class Tblnodes(models.Model):
    nodeid = models.IntegerField(db_column='nodeID', unique=True, blank=True, null=True)  # Field name made lowercase.
    room = models.ForeignKey('Tblrooms', models.DO_NOTHING, db_column='room', blank=True, null=True)
    firingsequence = models.IntegerField(db_column='firingSequence', blank=True, null=True)  # Field name made lowercase.

    def __str__(self):
        return str(self.nodeid) + ', ' + str(self.room)
    class Meta:
        managed = False
        db_table = 'tblnodes'


class Tblrooms(models.Model):
    designator = models.CharField(max_length=255, blank=True, null=True)
    width = models.FloatField(blank=True, null=True)
    length = models.FloatField(blank=True, null=True)

    def __str__(self):
        return str(self.designator)

    class Meta:
        managed = False
        db_table = 'tblrooms'

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = ('email', 'username',)

class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ('email', 'username',)

accounts/views.py
from django.shortcuts import render

# Create your views here.

pages/views.py
from django.views.generic import TemplateView
from django.shortcuts import render

from .models import *

class HomePageView(TemplateView):
    template_name = 'pages/home.html'


class AboutPageView(TemplateView):
    template_name = 'pages/about.html'


def index(request):
    all = Tbllocationdata.objects.order_by('stampedtime')
    user = Tblassets.objects.get(firstname='Brooklynn')
    badge = Tblbadges.objects.get(asset=user)
    all = all.filter(badgeid=badge.badgeid)
    raw_data_list = list()
    for row in all:
        r = Tblnodes.objects.filter(nodeid=row.nodeid)
        a = Tblbadges.objects.filter(badgeid=row.badgeid)
        if len(r) > 0:
            r = str(r[0].room)
        else:
            r = str(row.nodeid)
        if len(a) > 0:
            a = str(a[0].asset)
        else:
            a = str(row.badgeid)
        raw_data_list.append({'id': row.id, 'stampedtime': row.stampedtime, 'asset': a, 'room': r})
    # print(raw_data_list)
    # print(raw_data_list[0])
    context = {'raw_data_list': raw_data_list}
    return render(request, 'pages/rawlocation.html', context)

def detail(request, locdata_id):
    try:
        dp = Tbllocationdata.objects.get(id=locdata_id)
        r = Tblnodes.objects.filter(nodeid=dp.nodeid)
        a = Tblbadges.objects.filter(badgeid=dp.badgeid)
        if len(r) > 0:
            r = str(r[0].room)
        else:
            r = 'None Associated'
        if len(a) > 0:
            a = str(a[0].asset)
        else:
            a = 'None Associated'
        dpf = {'id': dp.id, 'stampedtime': dp.stampedtime, 'asset': a, 'room': r, 'badgeid': dp.badgeid, 'nodeid': dp.nodeid}
    except:
        return
    return render(request, 'pages/detail.html', {'dp': dpf})

def contactTracing(request):
    return render(request, 'pages/contactTracing.html')

def assetManagement(request):
    return render(request, 'pages/assetManagement.html')

def changePermissions(request):
    return render(request, 'pages/changePermissions.html')

def homepage(request):
    return render(request, 'pages/homepage.html')

def locationSurveillance(request, mode_id):
    return render(request, 'pages/locationSurveillance.html')

templates/403_csrf.html
{% extends '_base.html' %}

{% block title %}Forbidden (403){% endblock title %}

{% block content %}
<h1>Forbidden (403)</h1>
<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

templates/_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1">
<title>{% block title %}DjangoX{% endblock title %}</title>
<meta name="description" content="A framework for launching new Django projects quickly.">
<meta name="author" content="">
<link rel="shortcut icon" type="image/x-icon" href="{% static 'images/favicon.ico' %}">

{% block css %}
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

<link rel="stylesheet" href="{% static 'css/base.css' %}">
{% endblock %}
</head>

<body>
  <main role="main">
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
      <h5 class="my-0 mr-md-auto font-weight-normal">
        <a href="{% url 'home' %}">DjangoX</a>
      </h5>
      <a class="p-2 text-dark" href="{% url 'about' %}">About</a>
      <nav class="my-2 my-md-0 mr-md-3">
        {% if user.is_authenticated %}
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              {{ user.email }}
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
              <a class="dropdown-item" href="{% url 'account_change_password' %}">Change password</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'account_logout' %}">Log out</a>
            </div>
          </li>
        </ul>
        {% else %}
        <form class="form-inline ml-auto">
          <a href="{% url 'account_login' %}" class="btn btn-outline-secondary">Log in</a>
          <a href="{% url 'account_signup' %}" class="btn btn-primary ml-2">Sign up</a>
        </form>
        {% endif %}
      </nav>
    </div>
  </main>

  <div class="container">
    {% block content %}
      <p>Default content...</p>
    {% endblock content %}
  </div>

  <footer class="footer">
    <div class="container">
      <span class="text-muted">Footer...</span>
    </div>
  </footer>



  {% block javascript %}
  <!-- Bootstrap JavaScript -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha256-4+XzXVhsDmqanXGHaHvgh1gMQKX40OUvDEBTu8JcmNs=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

  <!-- 3rd party JavaScript -->

  <!-- Project JS -->
  <script src="{% static 'js/base.js' %}"></script>

  {% endblock javascript %}

</body>
</html>

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />
    <title>IR Location Tracking {% block title %}{% endblock %}</title>
  </head>
  <body>

    <div class="container">
      <div class="row">
        <div class="col-md-6 m-auto">
          {% block content %}{% endblock %}
        </div>
      </div>
    </div>
  </body>
</html>

templates/pages/about.html
{% extends '_base.html' %}

{% block title %}About page{% endblock %}

{% block content %}
<h1>About page</h1>
{% endblock content %}

templates/pages/assetManagement.html
{% extends 'base.html' %}
{% block content %}

<head>
<style>

</style>
</head>

<body>
<img src="/templates/pages/decorative_crimson.png" alt="decoration">
<p>yes this is asset management</p>
</body>
{% endblock %}

templates/pages/contactTracing.html
{% extends 'base.html' %}
{% block content %}
<a class="btn btn-secondary btn-sm mb-3" href="{% url 'polls:index' %}">Back to Home</a>
<h1 class="text-center mb-3">{{ question.question_text }}</h1>

{

templates/pages/detail.html
{% extends 'base.html' %}
{% block content %}
<a class="btn btn-secondary btn-sm mb-3" href="{% url 'locdata:index' %}">Back To Raw Data</a>
<h1 class="text-center mb-3">{{ dpf.stampedtime }}</h1>

{% if error_message %}
<p class="alert alert-danger">
	<strong>{{ error_message }}</strong>
</p>
{% endif %}

<dl class="dl-horizontal">
  <dt>Time Stamp</dt>
  <dd>{{dp.stampedtime}}</dd>
  <dt>Asset</dt>
  <dd>{{dp.asset}}</dd>
  <dt>Room</dt>
  <dd>{{dp.room}}</dd>
  <dt>NodeID</dt>
  <dd>{{dp.nodeid}}</dd>
    <dt>BadgeID</dt>
  <dd>{{dp.badgeid}}</dd>
    <dt>Data Entry ID</dt>
  <dd>{{dp.id}}</dd>
</dl>

<!--<form action="{% url 'locdata:index' %}" method="post">-->
<!--	{% csrf_token %}-->
<!--		<div class="form-check">-->
<!--			<input-->
<!--				type="radio"-->
<!--				name="choice"-->
<!--				class="form-check-input"-->
<!--				id="choice"-->
<!--				value="{{ dp.id }}"-->
<!--			/>-->
<!--			<label for="choice">{{ dp.asset }}</label-->
<!--			>-->
<!--		</div>-->
<!--	<input type="submit" value="Vote" class="btn btn-success btn-lg btn-block mt-4" />-->
<!--</form>-->
{% endblock %}

templates/pages/home.html
{% extends '_base.html' %}
{% load static %}

{% block title %}Home page{% endblock title %}

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
  <img src="{% static 'images/jakestupid.png' %}" class="img-fluid" alt="DjangoX logo"/>
  <p class="lead">A Django starter project with batteries.</p>
</div>
{% endblock content %}

templates/pages/homepage.html
{% extends 'base.html' %}
{% block content %}

<head>
<style>
.button {
	border: none;
	color: white;
	text-align: center;
	text-decoration: none;
	font-size: 16px;
	display: block;
	margin: 20px auto;
	cursor: pointer;
}

.button1 {background-color: Crimson; padding: 15px 43.5px; margin-top: 25px}
.button2 {background-color: SeaGreen; padding: 15px 36px;}
.button3 {background-color: RoyalBlue; padding: 15px 20px;}

subtext {
	border: none;
	color: black;
	text-align: center;
	padding-top: 80px;
	padding-bottom: 200px;
}

h2 {
	display: inline-block;
	margin-left: 50%;
	transform: translateX(-50%);
	padding-top: 60px;
	padding-bottom: 60px;

	text-align: center;
	font-size: 55px;
	white-space: nowrap;
}

</style>
</head>

<body>

<center><h2>Welcome to the Homepage!</h2></center>
<subtext><h4>What would you like to do?</h4><subtext>
<div><button class="button button1" onclick="window.location.href='/assetManagement';">Find an Asset</button></div>
<div><button class="button button2">Contact Tracing</button></div>
<div><button class="button button3">Change Permissions</button></div>

</body>
{% endblock %}

templates/pages/rawlocation.html
{% extends 'base.html' %}
{% block content %}
  <h1 class="text-center mb-3">Raw Data</h1>
  {% if raw_data_list %}
    {% for dataentry in raw_data_list %}
      <div class="card mb-3">
        <div class="card-body">
          <p class="lead">{{ dataentry.stampedtime }} , {{ dataentry.asset }} , {{ dataentry.room }}</p>
          <a href="{% url 'locdata:detail' dataentry.id %}" class="btn btn-primary btn-sm">View</a>
        </div>
      </div>
    {% endfor %}
  {% else %}
    <p>No polls available</p>
  {% endif %}
{% endblock %}